services:
  mysql:
    container_name: 'guide-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=tablohm'
      - 'MYSQL_PASSWORD=tablohm'
      - 'MYSQL_ROOT_PASSWORD=tablohm'
      - 'MYSQL_USER=winkler'
    ports:
      - '3306:3306'
